# Generated by Django 5.1.4 on 2025-01-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
