# Generated by Django 5.1.4 on 2025-01-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='Provide an URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.URLField(default='Provide an URL'),
        ),
    ]
